export type githubUser = {
  avatar_url: string,
  bio: string,
  blog: string,
  created_at: string,
  company: string,
  events_url: string,
  followers: number,
  followers_url: string,
  following: number,
  following_url: string,
  gists_url: string,
  html_url: string,
  id: number,
  login: string,
  name: string,
  node_id: string,
  public_repos: number,
  received_events_url: string,
  repos_url: string,
  starred_url: string,
  subscriptions_url: string,
  url: string,
}